### ISSUE TITLE
NodeJs Azure -- module azure-iothub not found

### ISSUE THREAD

**Issue by thomasvoorend** [sandervandevelde/Techdays2017#8]
Module azure-iothub is not found, other modules in package.json don't give any errors.

The error occurs at https://github.com/sandervandevelde/Techdays2017/blob/master/CommandsTTN.md after you run the script after step 23. (the module is imported at step 15)

There is no bugfix found yet.

`2017-10-04T12:04:10.702 Stream Analytics produced:  [ { count: 7, deviceid: 'predictive_maintenance_machine_t1' } ]
2017-10-04T12:04:10.780 Exception while executing function: Functions.IoTWorkshopEventHubFunction. mscorlib: Error: Cannot find module 'azure-iothub'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (D:\home\site\wwwroot\IoTWorkshopEventHubFunction\index.js:4:41)
    at D:\Program Files (x86)\SiteExtensions\Functions\1.0.11247\bin\azurefunctions\functions.js:99:24.
2017-10-04T12:04:10.966 Function completed (Failure, Id=08c17103-b293-444c-a2d2-4139dae45d9e, Duration=264ms)
`

**Comment by MarieGlas** [comment]
[
![screen shot 2017-10-04 at 15 36 29](https://user-images.githubusercontent.com/32485908/31178642-fed475a6-a919-11e7-8ca5-b29cdbea6edb.png)

**Comment by meneersnor** [comment]
Same here.

Loek

**Comment by bokse001** [comment]
Solved with installation of packages through console. Added to descriptions.
